using Microsoft.AspNetCore.Mvc;
using PokemonDatabase.Models;

namespace PokemonDatabase.Controllers;

public class PokemonController : Controller
{
    public IActionResult Table()
    {
        var pokemons = new List<Pokemon>
        {
            new Pokemon(001, "Bulbasaur", "Grass/Poison"),
            new Pokemon(002, "Ivysaur", "Grass/Poison"),
            new Pokemon(003, "Venusaur", "Grass/Poison"),
            new Pokemon(004, "Charmander", "Fire"),
            new Pokemon(005, "Charmeleon", "Fire"),
            new Pokemon(006, "Charizard", "Fire/Flying"),
            new Pokemon(007, "Squirtle", "Water"),
            new Pokemon(008, "Wartortle", "Water"),
            new Pokemon(009, "Blastoise", "Water"),
            new Pokemon(010, "Caterpie", "Bug"),
            new Pokemon(011, "Metapod", "Bug"),
            new Pokemon(012, "Butterfree", "Bug/Flying"),
            new Pokemon(013, "Weedle", "Bug/Poison"),
            new Pokemon(014, "Kakuna", "Bug/Poison"),
            new Pokemon(015, "Beedrill", "Bug/Poison"),
            new Pokemon(016, "Pidgey", "Normal/Flying"),
            new Pokemon(017, "Pidgeotto", "Normal/Flying"),
            new Pokemon(018, "Pidgeot", "Normal/Flying"),
            new Pokemon(019, "Rattata", "Normal"),
            new Pokemon(020, "Raticate", "Normal"),
            new Pokemon(021, "Spearow", "Normal/Flying"),
            new Pokemon(022, "Fearow", "Normal/Flying"),
            new Pokemon(023, "Ekans", "Poison"),
            new Pokemon(024, "Arbok", "Poison"),
            new Pokemon(025, "Pikachu", "Electric"),
            new Pokemon(026, "Raichu", "Electric"),
            new Pokemon(027, "Sandshrew", "Ground"),
            new Pokemon(028, "Sandslash", "Ground"),
            new Pokemon(029, "Nidoran♀", "Poison"),
            new Pokemon(030, "Nidorina", "Poison"),
            new Pokemon(031, "Nidoqueen", "Poison/Ground"),
            new Pokemon(032, "Nidoran♂", "Poison"),
            new Pokemon(033, "Nidorino", "Poison"),
            new Pokemon(034, "Nidoking", "Poison/Ground"),
            new Pokemon(035, "Clefairy", "Fairy"),
            new Pokemon(036, "Clefable", "Fairy"),
            new Pokemon(037, "Vulpix", "Fire"),
            new Pokemon(038, "Ninetales", "Fire"),
            new Pokemon(039, "Jigglypuff", "Normal/Fairy"),
            new Pokemon(040, "Wigglytuff", "Normal/Fairy"),
            new Pokemon(041, "Zubat", "Poison/Flying"),
            new Pokemon(042, "Golbat", "Poison/Flying"),
            new Pokemon(043, "Oddish", "Grass/Poison"),
            new Pokemon(044, "Gloom", "Grass/Poison"),
            new Pokemon(045, "Vileplume", "Grass/Poison"),
            new Pokemon(046, "Paras", "Bug/Grass"),
            new Pokemon(047, "Parasect", "Bug/Grass"),
            new Pokemon(048, "Venonat", "Bug/Poison"),
            new Pokemon(049, "Venomoth", "Bug/Poison"),
            new Pokemon(050, "Diglett", "Ground"),
            new Pokemon(051, "Dugtrio", "Ground"),
            new Pokemon(052, "Meowth", "Normal"),
            new Pokemon(053, "Persian", "Normal"),
            new Pokemon(054, "Psyduck", "Water"),
            new Pokemon(055, "Golduck", "Water"),
            new Pokemon(056, "Mankey", "Fighting"),
            new Pokemon(057, "Primeape", "Fighting"),
            new Pokemon(058, "Growlithe", "Fire"),
            new Pokemon(059, "Arcanine", "Fire"),
            new Pokemon(060, "Poliwag", "Water"),
            new Pokemon(061, "Poliwhirl", "Water"),
            new Pokemon(062, "Poliwrath", "Water/Fighting"),
            new Pokemon(063, "Abra", "Psychic"),
            new Pokemon(064, "Kadabra", "Psychic"),
            new Pokemon(065, "Alakazam", "Psychic"),
            new Pokemon(066, "Machop", "Fighting"),
            new Pokemon(067, "Machoke", "Fighting"),
            new Pokemon(068, "Machamp", "Fighting"),
            new Pokemon(069, "Bellsprout", "Grass/Poison"),
            new Pokemon(070, "Weepinbell", "Grass/Poison"),
            new Pokemon(071, "Victreebel", "Grass/Poison"),
            new Pokemon(072, "Tentacool", "Water/Poison"),
            new Pokemon(073, "Tentacruel", "Water/Poison"),
            new Pokemon(074, "Geodude", "Rock/Ground"),
            new Pokemon(075, "Graveler", "Rock/Ground"),
            new Pokemon(076, "Golem", "Rock/Ground"),
            new Pokemon(077, "Ponyta", "Fire"),
            new Pokemon(078, "Rapidash", "Fire"),
            new Pokemon(079, "Slowpoke", "Water/Psychic"),
            new Pokemon(080, "Slowbro", "Water/Psychic"),
            new Pokemon(081, "Magnemite", "Electric/Steel"),
            new Pokemon(082, "Magneton", "Electric/Steel"),
            new Pokemon(083, "Farfetch’d", "Normal/Flying"),
            new Pokemon(084, "Doduo", "Normal/Flying"),
            new Pokemon(085, "Dodrio", "Normal/Flying"),
            new Pokemon(086, "Seel", "Water"),
            new Pokemon(087, "Dewgong", "Water/Ice"),
            new Pokemon(088, "Grimer", "Poison"),
            new Pokemon(089, "Muk", "Poison"),
            new Pokemon(090, "Shellder", "Water"),
            new Pokemon(091, "Cloyster", "Water/Ice"),
            new Pokemon(092, "Gastly", "Ghost/Poison"),
            new Pokemon(093, "Haunter", "Ghost/Poison"),
            new Pokemon(094, "Gengar", "Ghost/Poison"),
            new Pokemon(095, "Onix", "Rock/Ground"),
            new Pokemon(096, "Drowzee", "Psychic"),
            new Pokemon(097, "Hypno", "Psychic"),
            new Pokemon(098, "Krabby", "Water"),
            new Pokemon(099, "Kingler", "Water"),
            new Pokemon(100, "Voltorb", "Electric"),
            new Pokemon(101, "Electrode", "Electric"),
            new Pokemon(102, "Exeggcute", "Grass/Psychic"),
            new Pokemon(103, "Exeggutor", "Grass/Psychic"),
            new Pokemon(104, "Cubone", "Ground"),
            new Pokemon(105, "Marowak", "Ground"),
            new Pokemon(106, "Hitmonlee", "Fighting"),
            new Pokemon(107, "Hitmonchan", "Fighting"),
            new Pokemon(108, "Lickitung", "Normal"),
            new Pokemon(109, "Koffing", "Poison"),
            new Pokemon(110, "Weezing", "Poison"),
            new Pokemon(111, "Rhyhorn", "Ground/Rock"),
            new Pokemon(112, "Rhydon", "Ground/Rock"),
            new Pokemon(113, "Chansey", "Normal"),
            new Pokemon(114, "Tangela", "Grass"),
            new Pokemon(115, "Kangaskhan", "Normal"),
            new Pokemon(116, "Horsea", "Water"),
            new Pokemon(117, "Seadra", "Water"),
            new Pokemon(118, "Goldeen", "Water"),
            new Pokemon(119, "Seaking", "Water"),
            new Pokemon(120, "Staryu", "Water"),
            new Pokemon(121, "Starmie", "Water/Psychic"),
            new Pokemon(122, "Mr. Mime", "Psychic/Fairy"),
            new Pokemon(123, "Scyther", "Bug/Flying"),
            new Pokemon(124, "Jynx", "Ice/Psychic"),
            new Pokemon(125, "Electabuzz", "Electric"),
            new Pokemon(126, "Magmar", "Fire"),
            new Pokemon(127, "Pinsir", "Bug"),
            new Pokemon(128, "Tauros", "Normal"),
            new Pokemon(129, "Magikarp", "Water"),
            new Pokemon(130, "Gyarados", "Water/Flying"),
            new Pokemon(131, "Lapras", "Water/Ice"),
            new Pokemon(132, "Ditto", "Normal"),
            new Pokemon(133, "Eevee", "Normal"),
            new Pokemon(134, "Vaporeon", "Water"),
            new Pokemon(135, "Jolteon", "Electric"),
            new Pokemon(136, "Flareon", "Fire"),
            new Pokemon(137, "Porygon", "Normal"),
            new Pokemon(138, "Omanyte", "Rock/Water"),
            new Pokemon(139, "Omastar", "Rock/Water"),
            new Pokemon(140, "Kabuto", "Rock/Water"),
            new Pokemon(141, "Kabutops", "Rock/Water"),
            new Pokemon(142, "Aerodactyl", "Rock/Flying"),
            new Pokemon(143, "Snorlax", "Normal"),
            new Pokemon(144, "Articuno", "Ice/Flying"),
            new Pokemon(145, "Zapdos", "Electric/Flying"),
            new Pokemon(146, "Moltres", "Fire/Flying"),
            new Pokemon(147, "Dratini", "Dragon"),
            new Pokemon(148, "Dragonair", "Dragon"),
            new Pokemon(149, "Dragonite", "Dragon/Flying"),
            new Pokemon(150, "Mewtwo", "Psychic"),
            new Pokemon(151, "Mew", "Psychic")
        };


        return (View(pokemons));
    }
}